# Generated by Django 5.0.1 on 2024-02-12 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppvinCartApp', '0007_alter_cart_user_alter_orders_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppvinCartApp.users'),
        ),
    ]
